language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '8'
  - '6'
before_script:
  - npm prune
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8